repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.297
    hooks:
      - id: ruff
        args: ["check", "."]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q
        language: system
        pass_filenames: false
        verbose: true
